/** Declaration file generated by dts-gen */
declare module 'sc2-sdk' {
    export function Initialize(config: any): any;

    export namespace Initialize {
        const prototype: {
        };
    }

    export function setBaseURL(baseUrl: string): void;
    export function setApp(app: any): void;
    export function setCallbackURL(callbackUrl: string): void;
    export function setAccessToken(accessToken: string): void;
    export function removeAccessToken(): void;
    export function setScope(scope: string []): void;
    export function me(callback: (error: Error, result: { account: string, metadata: object }) => void): void;
    export function revokeToken(callback: (error: Error, result: any) => void): void;
    export function sign(name: string, params: string [], redirectUri: string): string;
    export function broadcast(operations: object, callback: (error: Error, result: any) => void): void;
}

